source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JDSwiftAvatarProgress_Example', :exclusive => true do
  pod "JDSwiftAvatarProgress", :path => "../"
end

target 'JDSwiftAvatarProgress_Tests', :exclusive => true do
  pod "JDSwiftAvatarProgress", :path => "../"

  
end
